FROM ros:humble-ros-base-jammy

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ARG USERNAME=ubuntu
ARG TARGETPLATFORM

RUN apt update && \
    apt install -y tree wget curl git unzip zip && \
    if [ "$TARGETPLATFORM" = "linux/amd64" ]; then apt install -y vim; fi && \
    apt install -y zsh && \
    apt install -y libeigen3-dev && \
    apt install -y python3-colcon-common-extensions python3-rosdep python3-vcstool python3-pip python3-colcon-mixin && \
    rm -rf /var/lib/apt/lists/*

# setup user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID ${USERNAME} \
    && useradd --uid $USER_UID --gid $USER_GID -m ${USERNAME} \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}
USER ${USERNAME}

# zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
RUN git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions /home/${USERNAME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git /home/${USERNAME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g' /home/${USERNAME}/.zshrc
SHELL ["/bin/zsh", "-c"]

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.zsh" >> /home/${USERNAME}/.zshrc && \
    echo "source /usr/share/colcon_cd/function/colcon_cd.sh" >> /home/${USERNAME}/.zshrc && \
    echo "export _colcon_cd_root=/opt/ros/${ROS_DISTRO}/" >> /home/${USERNAME}/.zshrc && \
    echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.zsh" >> /home/${USERNAME}/.zshrc && \
    echo ": 1700000000:0;colcon build --mixin release" >> /home/${USERNAME}/.zsh_history && \
    rosdep update

WORKDIR /home/${USERNAME}/code

ENTRYPOINT [ "/bin/zsh" ]
