name: Build and Publish Docker Image

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [noetic-base, noetic-desktop, humble-base, humble-desktop, jazzy-base, jazzy-desktop]
        include:
          - variant: noetic-base
            tag: "noetic-base"
            dockerfile: "Dockerfile_noetic_base"
          - variant: noetic-desktop
            tag: "noetic-desktop"
            dockerfile: "Dockerfile_noetic_desktop"
          - variant: humble-base
            tag: "humble-base"
            dockerfile: "Dockerfile_humble_base"
          - variant: humble-desktop
            tag: "humble-desktop"
            dockerfile: "Dockerfile_humble_desktop"
          - variant: jazzy-base
            tag: "jazzy-base"
            dockerfile: "Dockerfile_jazzy_base"
          - variant: jazzy-desktop
            tag: "jazzy-desktop"
            dockerfile: "Dockerfile_jazzy_desktop"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository name
        id: repo
        run: echo "repository_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.repository_owner }}/ros:${{ matrix.tag }}
          platforms: linux/amd64, linux/arm64
